#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions
# Run Python scripts
NACA=4412
AOA=0
NPOINTS=300
LENGTH=1
CHORD=1
STL_NAME="naca${NACA}.stl"
comilla='"'
python3 scripts/naca_gen.py $NACA -n $NPOINTS -l $LENGTH -cl $CHORD -aoa $AOA
mkdir constant/geometry/
mv ${STL_NAME}  constant/geometry/
# Change blockMeshdict
sed -i "s/.*file.*/\t\t\t\tfile \t ${comilla}${STL_NAME}${comilla}; /" system/blockMeshDict

##Parallelization
nxpar=4                  # number of procs in x dir
nzpar=4                  # number of procs in z dir
nproc=$(nxpar * nzpar) # total number of procs
# Change decomposeParDict
sed -i "s/.*numberOfSubdomains.*/ numberOfSubdomains ${nproc}; /" system/decomposeParDict
sed -i "s/.*(.*/n (${nxpar} 1 ${nzpar}); /" system/decomposeParDict

touch sim.foam

application="$(getApplication)"

runApplication blockMesh
#runApplication transformPoints "scale=(1 0 1)"
runApplication extrudeMesh
runApplication decomposePar
runApplication renumberMesh
#runApplication $application
mpiexec -np $nproc $application -parallel
#runApplication reconstructPar
#------------------------------------------------------------------------------
~                                          
